### ISSUE TITLE
Build Failures on CentOS7 Invalid use of incomplete type 'class BitStream'

### ISSUE THREAD

**Issue by Otlichno** [Segs/Segs#660]
### Expected behavior
The build to complete succesfully
### Actual behavior/symptoms
Build errors out with output below.
### Steps to reproduce behavior/symptoms
On CentOS 7 with GCC 8.2.0
Checkout Develop branch and build with GCC 8.2.0
### SEGS version
Develop commit: be7d1c644a551eab9ebf4241cd01ff59e1dcd9ac
### Operating system
CentOS 7
### C++ compiler and version
8.2.0
### Other relevant information
[ 64%] Building CXX object Projects/CoX/Common/Messages/Map/CMakeFiles/MapServer_interface.dir/MapServerEvents.gen.cpp.o
In file included from /home/xxxx/project/bld/Projects/CoX/Common/Messages/Map/MapServerEvents.gen.cpp:2:0:
/home/xxxx/project/Segs-master/Projects/CoX/Common/Messages/Map/MapXferRequest.h: In member function ‘virtual void SEGSEvents::MapXferRequest::serializeto(BitStream&) const’:
/home/xxxx/project/Segs-master/Projects/CoX/Common/Messages/Map/MapXferRequest.h:26:21: error: invalid use of incomplete type ‘class BitStream’
                     bs.StorePackedBits(1, 11); // opcode
                     ^~
In file included from /home/xxxx/project/Segs-master/Projects/CoX/Common/Messages/Map/MapXferRequest.h:9:0,
                 from /home/xxxx/project/bld/Projects/CoX/Common/Messages/Map/MapServerEvents.gen.cpp:2:
/home/xxxx/project/Segs-master/Projects/CoX/Common/Messages/Map/GameCommand.h:13:7: note: forward declaration of ‘class BitStream’
 class BitStream;
       ^~~~~~~~~
In file included from /home/xxxx/project/bld/Projects/CoX/Common/Messages/Map/MapServerEvents.gen.cpp:2:0:
/home/xxxx/project/Segs-master/Projects/CoX/Common/Messages/Map/MapXferRequest.h:29:21: error: invalid use of incomplete type ‘class BitStream’
                     bs.StorePackedBits(1,unused1);
                     ^~
In file included from /home/xxxx/project/Segs-master/Projects/CoX/Common/Messages/Map/MapXferRequest.h:9:0,
                 from /home/xxxx/project/bld/Projects/CoX/Common/Messages/Map/MapServerEvents.gen.cpp:2:
/home/xxxx/project/Segs-master/Projects/CoX/Common/Messages/Map/GameCommand.h:13:7: note: forward declaration of ‘class BitStream’
 class BitStream;
       ^~~~~~~~~
In file included from /home/xxxx/project/bld/Projects/CoX/Common/Messages/Map/MapServerEvents.gen.cpp:2:0:
/home/xxxx/project/Segs-master/Projects/CoX/Common/Messages/Map/MapXferRequest.h:30:21: error: invalid use of incomplete type ‘class BitStream’
                     bs.StorePackedBits(1,unused2);
                     ^~
In file included from /home/xxxx/project/Segs-master/Projects/CoX/Common/Messages/Map/MapXferRequest.h:9:0,
                 from /home/xxxx/project/bld/Projects/CoX/Common/Messages/Map/MapServerEvents.gen.cpp:2:
/home/xxxx/project/Segs-master/Projects/CoX/Common/Messages/Map/GameCommand.h:13:7: note: forward declaration of ‘class BitStream’
 class BitStream;
       ^~~~~~~~~
In file included from /home/xxxx/project/bld/Projects/CoX/Common/Messages/Map/MapServerEvents.gen.cpp:2:0:
/home/xxxx/project/Segs-master/Projects/CoX/Common/Messages/Map/MapXferRequest.h:31:21: error: invalid use of incomplete type ‘class BitStream’
                     bs.StorePackedBits(1,ipaddr);
                     ^~
In file included from /home/xxxx/project/Segs-master/Projects/CoX/Common/Messages/Map/MapXferRequest.h:9:0,
                 from /home/xxxx/project/bld/Projects/CoX/Common/Messages/Map/MapServerEvents.gen.cpp:2:
/home/xxxx/project/Segs-master/Projects/CoX/Common/Messages/Map/GameCommand.h:13:7: note: forward declaration of ‘class BitStream’
 class BitStream;
       ^~~~~~~~~
In file included from /home/xxxx/project/bld/Projects/CoX/Common/Messages/Map/MapServerEvents.gen.cpp:2:0:
/home/xxxx/project/Segs-master/Projects/CoX/Common/Messages/Map/MapXferRequest.h:32:21: error: invalid use of incomplete type ‘class BitStream’
                     bs.StorePackedBits(1,unused3);
                     ^~
In file included from /home/xxxx/project/Segs-master/Projects/CoX/Common/Messages/Map/MapXferRequest.h:9:0,
                 from /home/xxxx/project/bld/Projects/CoX/Common/Messages/Map/MapServerEvents.gen.cpp:2:
/home/xxxx/project/Segs-master/Projects/CoX/Common/Messages/Map/GameCommand.h:13:7: note: forward declaration of ‘class BitStream’
 class BitStream;
       ^~~~~~~~~
In file included from /home/xxxx/project/bld/Projects/CoX/Common/Messages/Map/MapServerEvents.gen.cpp:2:0:
/home/xxxx/project/Segs-master/Projects/CoX/Common/Messages/Map/MapXferRequest.h:33:21: error: invalid use of incomplete type ‘class BitStream’
                     bs.StorePackedBits(1,port);
                     ^~
In file included from /home/xxxx/project/Segs-master/Projects/CoX/Common/Messages/Map/MapXferRequest.h:9:0,
                 from /home/xxxx/project/bld/Projects/CoX/Common/Messages/Map/MapServerEvents.gen.cpp:2:
/home/xxxx/project/Segs-master/Projects/CoX/Common/Messages/Map/GameCommand.h:13:7: note: forward declaration of ‘class BitStream’
 class BitStream;
       ^~~~~~~~~
In file included from /home/xxxx/project/bld/Projects/CoX/Common/Messages/Map/MapServerEvents.gen.cpp:2:0:
/home/xxxx/project/Segs-master/Projects/CoX/Common/Messages/Map/MapXferRequest.h:34:21: error: invalid use of incomplete type ‘class BitStream’
                     bs.StorePackedBits(1,unused4);
                     ^~
In file included from /home/xxxx/project/Segs-master/Projects/CoX/Common/Messages/Map/MapXferRequest.h:9:0,
                 from /home/xxxx/project/bld/Projects/CoX/Common/Messages/Map/MapServerEvents.gen.cpp:2:
/home/xxxx/project/Segs-master/Projects/CoX/Common/Messages/Map/GameCommand.h:13:7: note: forward declaration of ‘class BitStream’
 class BitStream;
       ^~~~~~~~~
In file included from /home/xxxx/project/bld/Projects/CoX/Common/Messages/Map/MapServerEvents.gen.cpp:2:0:
/home/xxxx/project/Segs-master/Projects/CoX/Common/Messages/Map/MapXferRequest.h:35:21: error: invalid use of incomplete type ‘class BitStream’
                     bs.StorePackedBits(1,m_map_cookie);
                     ^~
In file included from /home/xxxx/project/Segs-master/Projects/CoX/Common/Messages/Map/MapXferRequest.h:9:0,
                 from /home/xxxx/project/bld/Projects/CoX/Common/Messages/Map/MapServerEvents.gen.cpp:2:
/home/xxxx/project/Segs-master/Projects/CoX/Common/Messages/Map/GameCommand.h:13:7: note: forward declaration of ‘class BitStream’
 class BitStream;
       ^~~~~~~~~
In file included from /home/xxxx/project/Segs-master/Projects/CoX/Common/Messages/Map/GameCommandList.h:18:0,
                 from /home/xxxx/project/Segs-master/Projects/CoX/Common/Messages/Map/Browser.h:9,
                 from /home/xxxx/project/Segs-master/Projects/CoX/Common/Messages/Map/MapEvents.h:632,
                 from /home/xxxx/project/Segs-master/Projects/CoX/Common/Messages/Map/TradeWasUpdatedMessage.h:9,
                 from /home/xxxx/project/bld/Projects/CoX/Common/Messages/Map/MapServerEvents.gen.cpp:18:
/home/xxxx/project/Segs-master/Projects/CoX/Common/Messages/Map/DoorAnims.h: In member function ‘virtual void SEGSEvents::HasEnteredDoor::serializefrom(BitStream&)’:
/home/xxxx/project/Segs-master/Projects/CoX/Common/Messages/Map/DoorAnims.h:118:39: warning: unused parameter ‘bs’ [-Wunused-parameter]
         void serializefrom(BitStream &bs) override
                                       ^~
make[2]: *** [Projects/CoX/Common/Messages/Map/CMakeFiles/MapServer_interface.dir/MapServerEvents.gen.cpp.o] Error 1
make[1]: *** [Projects/CoX/Common/Messages/Map/CMakeFiles/MapServer_interface.dir/all] Error 2
make: *** [all] Error 2

**Comment by Otlichno** [comment]
GCC output for posterity:
$ gcc --version
gcc (GCC) 8.2.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by ldilley** [comment]
User confirmed that fresh build was successful. Chalking this up to pollution in user's local branch.
